apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: enriched-prompts
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 2592000000